# Generated by Django 5.1.7 on 2025-03-14 20:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_up', '0002_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
