# Generated by Django 5.1.7 on 2025-03-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_up', '0003_alter_membership_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
