# Generated by Django 5.1.7 on 2025-03-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_up', '0004_customer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
