# Generated by Django 5.1.7 on 2025-03-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_active_membership_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='membership_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
