# Generated by Django 5.1.7 on 2025-03-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_profile_membership_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='closed_for_maintenance',
            field=models.BooleanField(default=False),
        ),
    ]
