# Generated by Django 5.1.7 on 2025-03-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_closed_for_maintenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('reason', models.CharField(max_length=255)),
            ],
        ),
    ]
